import os
from PIL import Image

def convert_white_to_transparent(input_jpg, output_png, threshold=240):
    """
    Convert white background to transparent in an image.
    threshold: how close to white a pixel must be to be removed (0–255).
      Code initially generated by Microsoft Copilot
    """
    img = Image.open(input_jpg).convert("RGBA")
    datas = img.getdata()

    new_data = []
    for item in datas:
        r, g, b, a = item
        if r > threshold and g > threshold and b > threshold:
            # Make near-white pixels transparent
            new_data.append((255, 255, 255, 0))
        else:
            new_data.append(item)

    img.putdata(new_data)
    img.save(output_png, "PNG")
    print(f"Saved transparent image as {output_png}")

# Example usage:
script_dir = os.path.dirname(os.path.abspath(__file__))
jpg_path = os.path.join(script_dir, "cards", "pun1442.card.green.jpg")
png_out_path = os.path.join(script_dir, "cards", "pun1442.card.green.png")
convert_white_to_transparent(jpg_path, png_out_path)