import os
from PIL import Image
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter, landscape

def jpg_to_stacked_pdf(input_jpg, output_pdf, replication_count=5, x_offset=30, y_offset=20):
    """
    Convert a JPG image into a PDF with stacked overlapping copies.
    Code initially generated by Microsoft Copilot
    
    Parameters:
        input_jpg (str): Path to the input JPG image.
        output_pdf (str): Path to save the output PDF.
        replication_count (int): Number of stacked copies.
        x_offset (int): Horizontal offset for each subsequent copy.
        y_offset (int): Vertical offset for each subsequent copy.
    """
    # Load image
    img = Image.open(input_jpg)
    width, height = img.size
    
    # Create PDF canvas
    c = canvas.Canvas(output_pdf, pagesize=landscape(letter))

    #page_width, page_height = letter
    page_width, page_height = letter
    
    # Scale image if larger than page
    scale = min(page_width / width, page_height / height)
    scaled_width = width * scale
    scaled_height = height * scale
    
    base_x = 100
    base_y = 200


    # Draw stacked images
    for i in range(replication_count):
        x = base_x - i * x_offset
        y = base_y - i * y_offset

        c.drawImage(input_jpg, x, y, width=scaled_width, height=scaled_height, mask='auto')
    
    # Save PDF
    c.save()
    print(f"PDF saved to {output_pdf}")

# Example usage:
print("Current working directory:", os.getcwd())
script_dir = os.path.dirname(os.path.abspath(__file__))

# Build the path to the image relative to the script
img_path = os.path.join(script_dir, "cards", "pun1442.card.green.png")
out_path = os.path.join(script_dir, "stacked_output.pdf")


jpg_to_stacked_pdf(img_path, out_path, replication_count=6, x_offset=15, y_offset=15)